@extends('layouts.app')
@section('content')
<section class="bg-emerald-950 text-white">
    <div class="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-2 lg:items-center">
        <div><span class="font-bold uppercase tracking-[0.2em] text-amber-400">Every child deserves a future</span><h1 class="mt-5 text-5xl font-black leading-tight md:text-6xl">Together, we can build brighter futures.</h1><p class="mt-6 max-w-xl text-lg leading-8 text-emerald-100">We provide care, education, nutrition and opportunities that help children grow with dignity and hope.</p><div class="mt-8 flex flex-wrap gap-4"><a href="{{ route('donate') }}" class="rounded-full bg-amber-400 px-7 py-3 font-bold text-slate-950 hover:bg-amber-300">Donate Now</a><a href="{{ route('programs') }}" class="rounded-full border border-white/30 px-7 py-3 font-bold hover:bg-white/10">Explore Programs</a></div></div>
        <div class="rounded-3xl border border-white/10 bg-white/10 p-8 shadow-2xl"><p class="text-sm font-semibold uppercase tracking-widest text-amber-300">Our impact</p><div class="mt-8 grid grid-cols-2 gap-5"><div class="rounded-2xl bg-white/10 p-5"><strong class="text-4xl">250+</strong><p class="mt-2 text-emerald-100">Children supported</p></div><div class="rounded-2xl bg-white/10 p-5"><strong class="text-4xl">12</strong><p class="mt-2 text-emerald-100">Active programs</p></div><div class="rounded-2xl bg-white/10 p-5"><strong class="text-4xl">40+</strong><p class="mt-2 text-emerald-100">Volunteers</p></div><div class="rounded-2xl bg-white/10 p-5"><strong class="text-4xl">8</strong><p class="mt-2 text-emerald-100">Communities reached</p></div></div></div>
    </div>
</section>
<section class="mx-auto max-w-7xl px-6 py-20"><div class="max-w-2xl"><span class="font-bold text-emerald-700">WHAT WE DO</span><h2 class="mt-3 text-4xl font-black">Care that creates opportunity</h2><p class="mt-4 text-slate-600">Our programs are designed around children's safety, education, wellbeing and long-term development.</p></div><div class="mt-10 grid gap-6 md:grid-cols-3"><article class="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><div class="text-3xl">📚</div><h3 class="mt-5 text-xl font-bold">Education</h3><p class="mt-3 text-slate-600">School support, learning resources and skills development.</p></article><article class="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><div class="text-3xl">❤️</div><h3 class="mt-5 text-xl font-bold">Care & Wellbeing</h3><p class="mt-3 text-slate-600">A safe environment with nutrition, healthcare and emotional support.</p></article><article class="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><div class="text-3xl">🌱</div><h3 class="mt-5 text-xl font-bold">Future Skills</h3><p class="mt-3 text-slate-600">Practical skills and mentorship that prepare young people for independence.</p></article></div></section>
@endsection
