<?php
namespace App\Services;
use Illuminate\Support\Facades\Http;
class PaystackGateway implements PaymentGateway {
 private string $secret; private string $base='https://api.paystack.co';
 public function __construct(){ $this->secret=(string)config('services.paystack.secret_key',''); }
 private function request(){ if($this->secret==='') throw new \RuntimeException('Paystack secret key is not configured.'); return Http::withToken($this->secret)->acceptJson()->timeout(20); }
 public function initialize(array $payload): array { $r=$this->request()->post($this->base.'/transaction/initialize',['email'=>$payload['email'],'amount'=>(int)round($payload['amount']*100),'currency'=>strtoupper($payload['currency']??'NGN'),'reference'=>$payload['reference']??null,'callback_url'=>$payload['callback_url']??null,'metadata'=>$payload['metadata']??null]); if(!$r->successful()||!$r->json('status')) throw new \RuntimeException($r->json('message')?:'Unable to initialize payment.'); $d=$r->json('data',[]); return ['success'=>true,'reference'=>$d['reference']??null,'authorization_url'=>$d['authorization_url']??null,'access_code'=>$d['access_code']??null,'data'=>$d]; }
 public function verify(string $reference): array { $r=$this->request()->get($this->base.'/transaction/verify/'.urlencode($reference)); if(!$r->successful()||!$r->json('status')) throw new \RuntimeException($r->json('message')?:'Unable to verify payment.'); return ['success'=>true,'reference'=>$reference,'status'=>$r->json('data.status'),'data'=>$r->json('data',[])]; }
 public function createPlan(string $name,float $amount,string $interval,string $currency='NGN'): array { $r=$this->request()->post($this->base.'/plan',['name'=>$name,'amount'=>(int)round($amount*100),'interval'=>$interval,'currency'=>strtoupper($currency)]); if(!$r->successful()||!$r->json('status')) throw new \RuntimeException($r->json('message')?:'Unable to create Paystack plan.'); return $r->json('data',[]); }
 public function createSubscription(string $customerCode,string $planCode): array { $r=$this->request()->post($this->base.'/subscription',['customer'=>$customerCode,'plan'=>$planCode]); if(!$r->successful()||!$r->json('status')) throw new \RuntimeException($r->json('message')?:'Unable to create Paystack subscription.'); return $r->json('data',[]); }
 public function fetchCustomer(string $email): array { $r=$this->request()->get($this->base.'/customer/'.urlencode($email)); if(!$r->successful()||!$r->json('status')) throw new \RuntimeException($r->json('message')?:'Unable to fetch Paystack customer.'); return $r->json('data',[]); }
 public function fetchSubscription(string $code): array { $r=$this->request()->get($this->base.'/subscription/'.urlencode($code)); if(!$r->successful()||!$r->json('status')) throw new \RuntimeException($r->json('message')?:'Unable to fetch Paystack subscription.'); return $r->json('data',[]); }
 public function disableSubscription(string $code,string $token): array { $r=$this->request()->post($this->base.'/subscription/disable',['code'=>$code,'token'=>$token]); if(!$r->successful()||!$r->json('status')) throw new \RuntimeException($r->json('message')?:'Unable to cancel Paystack subscription.'); return $r->json('data',[]); }
}
