@extends('layouts.app')
@section('content')
<div class="min-h-screen bg-[#f5f8f6] text-slate-900" x-data="{menu:false, dark:false}" x-init="dark=localStorage.getItem('donor-dark')==='1'" :class="dark?'dark':''">
<div x-show="menu" x-cloak @click="menu=false" class="fixed inset-0 z-40 bg-slate-950/60 lg:hidden"></div>
<div class="flex min-h-screen">
<aside :class="menu?'translate-x-0':'-translate-x-full'" class="fixed inset-y-0 left-0 z-50 flex w-72 -translate-x-full flex-col bg-emerald-950 text-white shadow-2xl transition lg:static lg:translate-x-0">
<div class="border-b border-emerald-800/80 p-6"><a href="{{ route('home') }}" class="flex items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-2xl bg-amber-400 text-xl font-black text-emerald-950">♥</span><span><b class="block text-xl tracking-tight">Hope <span class="text-amber-300">&amp; Care</span></b><small class="font-bold uppercase tracking-[.28em] text-emerald-300">Donor Portal</small></span></a></div>
<nav class="flex-1 overflow-y-auto space-y-1 p-4 text-sm font-semibold">
<a href="{{ route('dashboard') }}" class="flex items-center gap-3 rounded-xl bg-emerald-700 px-4 py-3 shadow-lg shadow-emerald-950/20">⌂ <span>Dashboard</span></a>
<p class="px-4 pb-2 pt-7 text-[10px] uppercase tracking-[.2em] text-emerald-300">Giving</p>
<a href="{{ route('donate') }}" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">♡ <span>Make a Donation</span></a>
<a href="{{ route('donor.donations.index') }}" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">↻ <span>Donation History</span></a>
@if(Route::has('donor.recurring.index'))<a href="{{ route('donor.recurring.index') }}" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">⟳ <span>Recurring Giving</span></a>@endif
@if(Route::has('donor.receipt'))<a href="{{ route('donor.donations.index') }}" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">▣ <span>Receipts</span></a>@endif
<p class="mt-4 border-t border-emerald-800/80 px-4 pb-2 pt-7 text-[10px] uppercase tracking-[.2em] text-emerald-300">My Account</p>
<a href="{{ route('profile') }}" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">♙ <span>Profile</span></a>
<a href="{{ route('profile') }}" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">⚙ <span>Account Settings</span></a>
<a href="{{ route('profile') }}" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">◇ <span>Security</span></a>
@if(Route::has('donor.notifications.index'))<a href="{{ route('donor.notifications.index') }}" class="flex items-center justify-between rounded-xl px-4 py-3 hover:bg-white/10"><span>♧ &nbsp; Notifications</span><b class="rounded-full bg-emerald-600 px-2 py-0.5 text-[10px]">3</b></a>@endif
<p class="mt-4 border-t border-emerald-800/80 px-4 pb-2 pt-7 text-[10px] uppercase tracking-[.2em] text-emerald-300">Get Involved</p>
<a href="{{ route('volunteer.apply') }}" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">♧ <span>Volunteer</span></a>
<a href="{{ route('home') }}#programs" class="flex items-center gap-3 rounded-xl px-4 py-3 hover:bg-white/10">▣ <span>Programs &amp; Events</span></a>
</nav>
<div class="m-4 rounded-2xl bg-emerald-800 p-5"><b>Make an impact</b><p class="mt-2 text-xs leading-5 text-emerald-100">Your donation funds help provide care, education and opportunity.</p><a href="{{ route('donate') }}" class="mt-4 block rounded-xl bg-amber-400 px-4 py-3 text-center text-xs font-black text-emerald-950 hover:bg-amber-300">＋ Donate Funds</a></div>
</aside>
<main class="min-w-0 flex-1">
<header class="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div class="flex h-20 items-center gap-4 px-4 sm:px-8 lg:px-10"><button @click="menu=true" class="rounded-xl border border-emerald-200 p-2 text-xl text-emerald-800 lg:hidden">☰</button><div class="hidden max-w-xl flex-1 sm:block"><div class="rounded-xl border border-emerald-100 bg-slate-50 px-4 py-3 text-sm text-slate-400">⌕ &nbsp; Search your donations, campaigns and activity...</div></div><div class="ml-auto flex items-center gap-2 sm:gap-4"><button @click="dark=!dark;localStorage.setItem('donor-dark',dark?'1':'0')" class="rounded-xl border border-emerald-100 p-2 text-lg" title="Toggle theme">☼</button>@if(Route::has('donor.notifications.index'))<a href="{{ route('donor.notifications.index') }}" class="relative rounded-xl border border-transparent p-2 text-xl hover:bg-emerald-50">♧<span class="absolute right-1 top-1 grid h-4 min-w-4 place-items-center rounded-full bg-emerald-600 text-[9px] text-white">3</span></a>@endif<div class="hidden border-l border-slate-200 pl-4 sm:block"><b class="block text-sm">{{ auth()->user()->name }}</b><small class="text-slate-500">Donor</small></div><span class="grid h-10 w-10 place-items-center rounded-full bg-emerald-100 font-black text-emerald-800">{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span></div></div></header>
<div class="mx-auto max-w-[1500px] px-4 py-7 sm:px-8 lg:px-10">
<div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">My Giving Dashboard</p><h1 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Welcome back, {{ auth()->user()->name }}! 👋</h1><p class="mt-2 max-w-2xl text-slate-500">Manage your donation funds, track your impact and continue supporting children and young people.</p></div><a href="{{ route('donate') }}" class="rounded-xl bg-emerald-700 px-6 py-3 text-center font-bold text-white shadow-lg shadow-emerald-700/20 hover:bg-emerald-800">＋ Add Donation Funds</a></div>
<div class="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
<div class="rounded-2xl bg-gradient-to-br from-emerald-900 to-emerald-700 p-6 text-white shadow-lg shadow-emerald-900/15"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-emerald-100">Donation Funds</p><p class="mt-2 text-3xl font-black">₦{{ number_format($total,0) }}</p></div><span class="grid h-12 w-12 place-items-center rounded-full bg-white/10 text-2xl">♡</span></div><p class="mt-5 text-xs font-bold text-emerald-100">Available giving total · completed donations</p><a href="{{ route('donate') }}" class="mt-4 inline-block rounded-lg bg-white px-4 py-2 text-xs font-black text-emerald-800">Donate funds</a></div>
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">Total Donations</p><p class="mt-2 text-3xl font-black">{{ $count }}</p></div><span class="grid h-12 w-12 place-items-center rounded-full bg-emerald-50 text-xl text-emerald-700">▣</span></div><p class="mt-5 text-xs font-bold text-emerald-700">{{ $completedCount }} completed gifts</p></div>
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">This Year</p><p class="mt-2 text-3xl font-black">₦{{ number_format($yearTotal,0) }}</p></div><span class="grid h-12 w-12 place-items-center rounded-full bg-amber-50 text-xl text-amber-600">↗</span></div><p class="mt-5 text-xs font-bold text-emerald-700">Your giving impact this year</p></div>
<div class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">Active Campaigns</p><p class="mt-2 text-3xl font-black">{{ $activeCampaigns }}</p></div><span class="grid h-12 w-12 place-items-center rounded-full bg-sky-50 text-xl text-sky-600">◇</span></div><a href="{{ route('home') }}#programs" class="mt-5 inline-block text-xs font-bold text-emerald-700">Explore campaigns →</a></div>
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-12">
<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 xl:col-span-8"><div class="flex items-center justify-between"><div><h2 class="text-lg font-black">Donation Overview</h2><p class="text-sm text-slate-500">Your completed giving over the last six months</p></div><span class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">6 months</span></div><div class="mt-6 overflow-x-auto"><svg viewBox="0 0 520 230" class="h-64 w-full min-w-[500px]" role="img" aria-label="Donation overview chart"><line x1="40" y1="190" x2="500" y2="190" stroke="currentColor" class="text-slate-200"/><line x1="40" y1="115" x2="500" y2="115" stroke="currentColor" class="text-slate-100"/><line x1="40" y1="45" x2="500" y2="45" stroke="currentColor" class="text-slate-100"/><polyline points="{{ $chartPoints }}" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" class="text-emerald-600"/>@foreach($months as $i=>$month) @php $x=42+($i*94);$y=190-(($month['amount']/$chartMax)*145);@endphp<circle cx="{{ $x }}" cy="{{ $y }}" r="5" class="fill-emerald-600"/><text x="{{ $x }}" y="215" text-anchor="middle" font-size="12" class="fill-slate-500">{{ $month['label'] }}</text>@endforeach</svg></div></section>
<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 xl:col-span-4"><div class="flex items-center justify-between"><div><h2 class="text-lg font-black">Donation Funds</h2><p class="text-sm text-slate-500">Your giving summary</p></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Active</span></div><div class="mt-7 rounded-2xl bg-emerald-50 p-5"><p class="text-xs font-bold uppercase tracking-wider text-emerald-700">Total contributed</p><p class="mt-2 text-3xl font-black text-emerald-950">₦{{ number_format($total,2) }}</p><p class="mt-2 text-xs text-emerald-700">{{ $completedCount }} completed donations</p></div><a href="{{ route('donate') }}" class="mt-5 flex items-center justify-between rounded-xl border border-emerald-200 p-4 text-sm font-bold text-emerald-800 hover:bg-emerald-50"><span>Give more funds</span><span>→</span></a></section>
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-12"><section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 xl:col-span-8"><div class="flex items-center justify-between border-b p-6"><div><h2 class="text-lg font-black">Recent Donations</h2><p class="text-sm text-slate-500">Track your latest contributions and statuses</p></div><a href="{{ route('donor.donations.index') }}" class="text-sm font-bold text-emerald-700">View all →</a></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-6 py-4">Date</th><th class="px-6 py-4">Amount</th><th class="px-6 py-4">Method</th><th class="px-6 py-4">Status</th></tr></thead><tbody class="divide-y">@forelse($donations as $d)<tr class="hover:bg-emerald-50/40"><td class="whitespace-nowrap px-6 py-4">{{ $d->created_at->format('M d, Y') }}</td><td class="whitespace-nowrap px-6 py-4 font-black">{{ $d->currency }} {{ number_format($d->amount,2) }}</td><td class="px-6 py-4">{{ $d->payment_method?:'—' }}</td><td class="px-6 py-4"><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold capitalize text-emerald-700">{{ $d->status }}</span></td></tr>@empty<tr><td colspan="4" class="px-6 py-12 text-center text-slate-500">Your donation history will appear here.</td></tr>@endforelse</tbody></table></div><div class="border-t p-5">{{ $donations->links() }}</div></section>
<aside class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 xl:col-span-4"><h2 class="text-lg font-black">Quick Actions</h2><div class="mt-4 space-y-3">@foreach([['Add Donation Funds',route('donate'),'Support a child or campaign'],['Donation History',route('donor.donations.index'),'Review all your contributions'],['Become a Volunteer',route('volunteer.apply'),'Give your time and skills'],['View Campaigns',route('home').'#programs','Choose where to make an impact'],['Profile & Security',route('profile'),'Manage your account']] as $a)<a href="{{ $a[1] }}" class="flex items-center justify-between rounded-xl bg-slate-50 p-4 hover:bg-emerald-50"><span><b class="block text-sm text-emerald-800">{{ $a[0] }}</b><small class="text-xs text-slate-500">{{ $a[2] }}</small></span><span class="text-emerald-700">→</span></a>@endforeach</div></aside></div>
</div></main></div></div>
@endsection
