<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Admin Dashboard · Hope & Care</title>
<script src="https://cdn.tailwindcss.com"></script><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script src="https://unpkg.com/lucide@latest"></script>
<style>body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.sidebar{background:linear-gradient(180deg,#004d3b 0%,#003c30 100%)}.soft{box-shadow:0 5px 22px rgba(15,23,42,.07)}.nav-active{background:linear-gradient(90deg,#087d45,#07934e)}</style>
</head>
<body class="bg-[#f7f9fb] text-slate-900">
<div class="min-h-screen lg:flex">
<aside id="sidebar" class="sidebar fixed inset-y-0 left-0 z-50 w-[242px] -translate-x-full text-white transition-transform lg:static lg:translate-x-0">
<div class="flex h-full flex-col">
<div class="flex items-center gap-3 border-b border-white/10 px-5 py-5"><div class="flex h-12 w-12 items-center justify-center rounded-full border-2 border-amber-400 bg-white/10"><i data-lucide="house-heart" class="h-7 w-7 text-amber-300"></i></div><div><div class="text-lg font-semibold leading-none">Hope & Care</div><div class="mt-1 text-[11px] font-bold tracking-[.28em] text-amber-300">ORPHANAGE</div></div></div>
<nav class="flex-1 space-y-1 overflow-y-auto px-3 py-5 text-[14px]">
@php($links=[['LayoutDashboard','Dashboard','admin.dashboard'],['UsersRound','Children','admin.children.index'],['WalletCards','Donations','admin.donations.index'],['Megaphone','Campaigns','admin.campaigns.index'],['Users','Volunteers','admin.volunteers.index'],['ReceiptText','Expenses','admin.expenses.index'],['Boxes','Inventory','admin.inventory.index'],['GraduationCap','Education','admin.education.index'],['HeartPulse','Healthcare','admin.healthcare.index'],['CalendarDays','Events','admin.events.index'],['PanelsTopLeft','CMS & Pages','admin.posts.index'],['Images','Gallery','admin.gallery.index'],['Mail','Messages','admin.messages.index'],['MailPlus','Newsletter','admin.newsletter.index'],['ChartNoAxesCombined','Reports','admin.reports.index'],['ScrollText','Audit Logs','admin.audit.index'],['Settings','Settings','admin.settings.edit']])
@foreach($links as $link)<a href="{{ Route::has($link[2]) ? route($link[2]) : '#' }}" class="{{ request()->routeIs($link[2])?'nav-active shadow-lg':'' }} flex items-center gap-3 rounded-lg px-3 py-2.5 font-medium transition hover:bg-white/10"><i data-lucide="{{ $link[0] }}" class="h-[18px] w-[18px]"></i><span>{{ $link[1] }}</span>@if($link[1]==='Messages')<span class="ml-auto rounded-full bg-emerald-400 px-2 py-0.5 text-[10px] font-bold">{{ $stats['pending_donations'] ?? 0 }}</span>@endif</a>@endforeach
</nav><div class="border-t border-white/10 p-4"><button id="themeToggle" class="flex w-full items-center justify-between rounded-xl px-2 py-2 text-sm text-emerald-50 hover:bg-white/10"><span class="flex items-center gap-2"><i data-lucide="moon" class="h-4 w-4"></i>Dark Mode</span><span class="h-5 w-9 rounded-full bg-white/80 p-0.5"><span class="block h-4 w-4 rounded-full bg-emerald-600"></span></span></button></div>
</div></aside>
<div class="min-w-0 flex-1">
<header class="sticky top-0 z-40 flex h-[63px] items-center justify-between border-b bg-white/95 px-4 backdrop-blur sm:px-6"><div class="flex items-center gap-4"><button id="menuBtn" class="rounded-lg p-2 text-slate-500 hover:bg-slate-100 lg:hidden"><i data-lucide="menu" class="h-5 w-5"></i></button><div class="relative hidden md:block"><i data-lucide="search" class="absolute left-3 top-2.5 h-4 w-4 text-slate-400"></i><input class="w-[355px] rounded-lg border border-slate-200 bg-white py-2 pl-10 pr-4 text-sm outline-none focus:border-emerald-500" placeholder="Search anything..."></div></div><div class="flex items-center gap-4"><button class="relative text-slate-500"><i data-lucide="bell" class="h-5 w-5"></i><span class="absolute -right-2 -top-2 rounded-full bg-emerald-700 px-1.5 text-[9px] text-white">5</span></button><button class="relative text-slate-500"><i data-lucide="mail" class="h-5 w-5"></i><span class="absolute -right-2 -top-2 rounded-full bg-emerald-700 px-1.5 text-[9px] text-white">3</span></button><div class="hidden h-7 w-px bg-slate-200 sm:block"></div><div class="flex items-center gap-3"><div class="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-100 font-bold text-emerald-800">A</div><div class="hidden sm:block"><p class="text-sm font-semibold">Admin User</p><p class="text-xs text-slate-500">Super Admin</p></div><i data-lucide="chevron-down" class="hidden h-4 w-4 sm:block"></i></div></div></header>
<main class="mx-auto max-w-[1280px] space-y-5 p-4 sm:p-6">
<div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-[26px] font-bold tracking-tight">Welcome back, Admin! <span>👋</span></h1><p class="mt-1 text-sm text-slate-500">Here's what's happening in your orphanage today.</p></div><a href="{{ route('home') }}" class="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-800"><i data-lucide="globe-2" class="h-4 w-4"></i>View Website</a></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">
@foreach([['Total Children',$stats['children'] ?? 0,'↑ 5 this month','UsersRound','emerald'],['Total Donors',$stats['donors'] ?? 0,'↑ 18 this month','UserRound','emerald'],['Total Donations','₦'.number_format($stats['donations'] ?? 0),'↑ 24.5% this month','BadgeDollarSign','emerald'],['Pending Donations',$stats['pending_donations'] ?? 0,'View pending','Clock3','amber'],['Volunteers',$stats['volunteers'] ?? 0,'↑ 11 this month','Users','emerald'],['Active Campaigns',$stats['campaigns'] ?? 0,'View all','Target','emerald']] as $c)<div class="soft rounded-xl bg-white p-4 ring-1 ring-slate-100"><div class="flex items-center gap-3"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full {{ $c[4]==='amber'?'bg-amber-50 text-amber-500':'bg-emerald-50 text-emerald-600' }}"><i data-lucide="{{ $c[3] }}" class="h-5 w-5"></i></div><div class="min-w-0"><p class="text-xs text-slate-500">{{ $c[0] }}</p><p class="mt-1 truncate text-xl font-bold">{{ $c[1] }}</p></div></div><p class="mt-3 text-[11px] font-semibold {{ $c[4]==='amber'?'text-amber-600':'text-emerald-600' }}">{{ $c[2] }}</p></div>@endforeach
</div>
<div class="grid gap-4 lg:grid-cols-4"><div class="soft rounded-xl bg-white p-5 lg:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-bold">Donation Overview <span class="font-normal text-slate-500">(Last 6 Months)</span></h2></div><select class="rounded-lg border border-slate-200 px-3 py-1.5 text-xs"><option>Last 6 months</option></select></div><div class="mt-3 h-[260px]"><canvas id="donationChart"></canvas></div></div>
<div class="soft rounded-xl bg-white p-5"><h2 class="font-bold">Recent Activities</h2><div class="mt-4 space-y-4">@forelse($recentActivity as $a)<div class="flex gap-3"><div class="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><i data-lucide="activity" class="h-4 w-4"></i></div><div class="min-w-0"><p class="text-xs font-semibold">{{ $a->description ?: $a->action }}</p><p class="text-[10px] text-slate-400">{{ optional($a->created_at)->diffForHumans() }}</p></div></div>@empty<p class="py-10 text-center text-xs text-slate-400">No activity yet.</p>@endforelse</div><a href="{{ Route::has('admin.audit.index')?route('admin.audit.index'):'#' }}" class="mt-4 block rounded-lg border py-2 text-center text-xs font-semibold text-emerald-700">View all activities</a></div>
<div class="soft rounded-xl bg-white p-5"><h2 class="font-bold">Campaign Progress</h2><div class="mt-4 space-y-5">@forelse($campaigns as $campaign) @php($pct=$campaign->target_amount>0?min(100,round(($campaign->current_amount/$campaign->target_amount)*100)):0)<div><div class="flex justify-between gap-2 text-xs font-semibold"><span class="truncate">{{ $campaign->title }}</span><span class="text-emerald-700">{{ $pct }}%</span></div><p class="mt-1 text-[10px] text-slate-500">₦{{ number_format($campaign->current_amount,0) }} of ₦{{ number_format($campaign->target_amount,0) }}</p><div class="mt-2 h-1.5 rounded-full bg-slate-100"><div class="h-1.5 rounded-full bg-emerald-600" style="width:{{ $pct }}%"></div></div></div>@empty<p class="py-10 text-center text-xs text-slate-400">No active campaigns.</p>@endforelse</div><a href="{{ route('admin.campaigns.index') }}" class="mt-4 block rounded-lg border py-2 text-center text-xs font-semibold text-emerald-700">View all campaigns</a></div></div>
<div class="grid gap-4 lg:grid-cols-3"><div class="soft overflow-hidden rounded-xl bg-white lg:col-span-2"><div class="flex items-center justify-between border-b px-5 py-4"><h2 class="font-bold">Recent Donations</h2><a href="{{ route('admin.donations.index') }}" class="text-xs font-semibold text-emerald-700">View all</a></div><div class="overflow-x-auto"><table class="w-full text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th class="px-5 py-3">Donor</th><th>Amount</th><th>Payment Method</th><th>Date</th><th>Status</th></tr></thead><tbody class="divide-y">@forelse($recentDonations as $d)<tr><td class="px-5 py-3 font-semibold">{{ $d->name ?: 'Anonymous' }}</td><td>₦{{ number_format($d->amount,0) }}</td><td>{{ $d->payment_method ?: '—' }}</td><td>{{ optional($d->created_at)->format('M d, Y') }}</td><td><span class="rounded-full {{ $d->status==='completed'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700' }} px-2 py-1 text-[10px] font-bold">{{ ucfirst($d->status) }}</span></td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-400">No donations yet.</td></tr>@endforelse</tbody></table></div></div>
<div class="soft rounded-xl bg-white p-5"><h2 class="font-bold">Quick Actions</h2><div class="mt-4 grid grid-cols-2 gap-2">@foreach([['UserPlus','Add Child','admin.children.index'],['HeartHandshake','New Donation','admin.donations.index'],['Receipt','Add Expense','admin.expenses.index'],['Megaphone','Add Campaign','admin.campaigns.index'],['UserRoundPlus','New Volunteer','admin.volunteers.index'],['CalendarPlus','Add Event','admin.events.index'],['GraduationCap','Add Education','admin.education.index'],['MessageCircle','Send Message','admin.messages.index']] as $a)<a href="{{ Route::has($a[2])?route($a[2]):'#' }}" class="rounded-lg bg-emerald-50/70 p-3 text-center text-[10px] font-semibold text-emerald-800 hover:bg-emerald-100"><i data-lucide="{{ $a[0] }}" class="mx-auto mb-1 h-4 w-4"></i>{{ $a[1] }}</a>@endforeach</div></div></div>
<div class="flex items-center justify-between border-t pt-5 text-[10px] text-slate-400"><span>© {{ date('Y') }} Hope & Care Orphanage. All rights reserved.</span><span>Made with <span class="text-red-500">♥</span> for a better tomorrow.</span></div>
</main></div></div>
<script>lucide.createIcons();document.getElementById('menuBtn')?.addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('-translate-x-full'));new Chart(document.getElementById('donationChart'),{type:'line',data:{labels:@json($chartLabels??[]),datasets:[{label:'Donations',data:@json($chartData??[]),borderWidth:2,tension:.4,fill:true,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:'#eef2f7'},ticks:{callback:v=>v>=1000000?(v/1000000)+'M':v>=1000?(v/1000)+'K':v}}}}}});</script>
</body></html>
